// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: document_recovery.proto

package document

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentRecoveryService_GetLatestSnapshot_FullMethodName  = "/proto.DocumentRecoveryService/GetLatestSnapshot"
	DocumentRecoveryService_GetOperationsSince_FullMethodName = "/proto.DocumentRecoveryService/GetOperationsSince"
)

// DocumentRecoveryServiceClient is the client API for DocumentRecoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentRecoveryServiceClient interface {
	GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error)
	GetOperationsSince(ctx context.Context, in *GetOperationsSinceRequest, opts ...grpc.CallOption) (*GetOperationsSinceResponse, error)
}

type documentRecoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentRecoveryServiceClient(cc grpc.ClientConnInterface) DocumentRecoveryServiceClient {
	return &documentRecoveryServiceClient{cc}
}

func (c *documentRecoveryServiceClient) GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, DocumentRecoveryService_GetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentRecoveryServiceClient) GetOperationsSince(ctx context.Context, in *GetOperationsSinceRequest, opts ...grpc.CallOption) (*GetOperationsSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationsSinceResponse)
	err := c.cc.Invoke(ctx, DocumentRecoveryService_GetOperationsSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentRecoveryServiceServer is the server API for DocumentRecoveryService service.
// All implementations must embed UnimplementedDocumentRecoveryServiceServer
// for forward compatibility.
type DocumentRecoveryServiceServer interface {
	GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error)
	GetOperationsSince(context.Context, *GetOperationsSinceRequest) (*GetOperationsSinceResponse, error)
	mustEmbedUnimplementedDocumentRecoveryServiceServer()
}

// UnimplementedDocumentRecoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentRecoveryServiceServer struct{}

func (UnimplementedDocumentRecoveryServiceServer) GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshot not implemented")
}
func (UnimplementedDocumentRecoveryServiceServer) GetOperationsSince(context.Context, *GetOperationsSinceRequest) (*GetOperationsSinceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperationsSince not implemented")
}
func (UnimplementedDocumentRecoveryServiceServer) mustEmbedUnimplementedDocumentRecoveryServiceServer() {
}
func (UnimplementedDocumentRecoveryServiceServer) testEmbeddedByValue() {}

// UnsafeDocumentRecoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentRecoveryServiceServer will
// result in compilation errors.
type UnsafeDocumentRecoveryServiceServer interface {
	mustEmbedUnimplementedDocumentRecoveryServiceServer()
}

func RegisterDocumentRecoveryServiceServer(s grpc.ServiceRegistrar, srv DocumentRecoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentRecoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentRecoveryService_ServiceDesc, srv)
}

func _DocumentRecoveryService_GetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentRecoveryServiceServer).GetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentRecoveryService_GetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentRecoveryServiceServer).GetLatestSnapshot(ctx, req.(*GetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentRecoveryService_GetOperationsSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationsSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentRecoveryServiceServer).GetOperationsSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentRecoveryService_GetOperationsSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentRecoveryServiceServer).GetOperationsSince(ctx, req.(*GetOperationsSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentRecoveryService_ServiceDesc is the grpc.ServiceDesc for DocumentRecoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentRecoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DocumentRecoveryService",
	HandlerType: (*DocumentRecoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSnapshot",
			Handler:    _DocumentRecoveryService_GetLatestSnapshot_Handler,
		},
		{
			MethodName: "GetOperationsSince",
			Handler:    _DocumentRecoveryService_GetOperationsSince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "document_recovery.proto",
}
