// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: document_recovery.proto

package document

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotRequest) Reset() {
	*x = GetLatestSnapshotRequest{}
	mi := &file_document_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotRequest) ProtoMessage() {}

func (x *GetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_document_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestSnapshotRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentText  string                 `protobuf:"bytes,1,opt,name=document_text,json=documentText,proto3" json:"document_text,omitempty"`
	LamportClock  int64                  `protobuf:"varint,2,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotResponse) Reset() {
	*x = GetLatestSnapshotResponse{}
	mi := &file_document_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotResponse) ProtoMessage() {}

func (x *GetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_document_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestSnapshotResponse) GetDocumentText() string {
	if x != nil {
		return x.DocumentText
	}
	return ""
}

func (x *GetLatestSnapshotResponse) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *GetLatestSnapshotResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetOperationsSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FromClock     int64                  `protobuf:"varint,2,opt,name=from_clock,json=fromClock,proto3" json:"from_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationsSinceRequest) Reset() {
	*x = GetOperationsSinceRequest{}
	mi := &file_document_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationsSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationsSinceRequest) ProtoMessage() {}

func (x *GetOperationsSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationsSinceRequest.ProtoReflect.Descriptor instead.
func (*GetOperationsSinceRequest) Descriptor() ([]byte, []int) {
	return file_document_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationsSinceRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetOperationsSinceRequest) GetFromClock() int64 {
	if x != nil {
		return x.FromClock
	}
	return 0
}

type GetOperationsSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationsSinceResponse) Reset() {
	*x = GetOperationsSinceResponse{}
	mi := &file_document_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationsSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationsSinceResponse) ProtoMessage() {}

func (x *GetOperationsSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationsSinceResponse.ProtoReflect.Descriptor instead.
func (*GetOperationsSinceResponse) Descriptor() ([]byte, []int) {
	return file_document_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *GetOperationsSinceResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	LamportClock  int64                  `protobuf:"varint,2,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_document_recovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_document_recovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_document_recovery_proto_rawDescGZIP(), []int{4}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *Operation) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_document_recovery_proto protoreflect.FileDescriptor

const file_document_recovery_proto_rawDesc = "" +
	"\n" +
	"\x17document_recovery.proto\x12\x05proto\";\n" +
	"\x18GetLatestSnapshotRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"{\n" +
	"\x19GetLatestSnapshotResponse\x12#\n" +
	"\rdocument_text\x18\x01 \x01(\tR\fdocumentText\x12#\n" +
	"\rlamport_clock\x18\x02 \x01(\x03R\flamportClock\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"[\n" +
	"\x19GetOperationsSinceRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"from_clock\x18\x02 \x01(\x03R\tfromClock\"N\n" +
	"\x1aGetOperationsSinceResponse\x120\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x10.proto.OperationR\n" +
	"operations\"\x97\x01\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12#\n" +
	"\rlamport_clock\x18\x02 \x01(\x03R\flamportClock\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text2\xcc\x01\n" +
	"\x17DocumentRecoveryService\x12V\n" +
	"\x11GetLatestSnapshot\x12\x1f.proto.GetLatestSnapshotRequest\x1a .proto.GetLatestSnapshotResponse\x12Y\n" +
	"\x12GetOperationsSince\x12 .proto.GetOperationsSinceRequest\x1a!.proto.GetOperationsSinceResponseBZ\n" +
	"\x1dcom.doceditor.docmanager.grpcB\x15DocumentRecoveryProtoZ\"custom_docs.com/m/v2/grpc/documentb\x06proto3"

var (
	file_document_recovery_proto_rawDescOnce sync.Once
	file_document_recovery_proto_rawDescData []byte
)

func file_document_recovery_proto_rawDescGZIP() []byte {
	file_document_recovery_proto_rawDescOnce.Do(func() {
		file_document_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_recovery_proto_rawDesc), len(file_document_recovery_proto_rawDesc)))
	})
	return file_document_recovery_proto_rawDescData
}

var file_document_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_document_recovery_proto_goTypes = []any{
	(*GetLatestSnapshotRequest)(nil),   // 0: proto.GetLatestSnapshotRequest
	(*GetLatestSnapshotResponse)(nil),  // 1: proto.GetLatestSnapshotResponse
	(*GetOperationsSinceRequest)(nil),  // 2: proto.GetOperationsSinceRequest
	(*GetOperationsSinceResponse)(nil), // 3: proto.GetOperationsSinceResponse
	(*Operation)(nil),                  // 4: proto.Operation
}
var file_document_recovery_proto_depIdxs = []int32{
	4, // 0: proto.GetOperationsSinceResponse.operations:type_name -> proto.Operation
	0, // 1: proto.DocumentRecoveryService.GetLatestSnapshot:input_type -> proto.GetLatestSnapshotRequest
	2, // 2: proto.DocumentRecoveryService.GetOperationsSince:input_type -> proto.GetOperationsSinceRequest
	1, // 3: proto.DocumentRecoveryService.GetLatestSnapshot:output_type -> proto.GetLatestSnapshotResponse
	3, // 4: proto.DocumentRecoveryService.GetOperationsSince:output_type -> proto.GetOperationsSinceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_document_recovery_proto_init() }
func file_document_recovery_proto_init() {
	if File_document_recovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_recovery_proto_rawDesc), len(file_document_recovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_recovery_proto_goTypes,
		DependencyIndexes: file_document_recovery_proto_depIdxs,
		MessageInfos:      file_document_recovery_proto_msgTypes,
	}.Build()
	File_document_recovery_proto = out.File
	file_document_recovery_proto_goTypes = nil
	file_document_recovery_proto_depIdxs = nil
}
