apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  selector:
    app: authentication-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
